### ISSUE TITLE
Doesn't build on Linux with nightly toolchain

### ISSUE THREAD

**Issue by osa1** [crossterm-rs/crossterm#430]
```
crossterm git:(master) $ git rev-parse HEAD
88add302cd8f006704b712c9f6aa624104635c71
crossterm git:(master) $ rustc --version
rustc 1.45.0-nightly (a74d1862d 2020-05-14)
crossterm git:(master) $ cargo --version
cargo 1.45.0-nightly (cb06cb269 2020-05-08)
crossterm git:(master) $ cargo build
    Updating crates.io index
   Compiling libc v0.2.70
   Compiling cfg-if v0.1.10
   Compiling log v0.4.8
   Compiling scopeguard v1.1.0
   Compiling bitflags v1.2.1
   Compiling slab v0.4.2
   Compiling smallvec v1.4.0
   Compiling arc-swap v0.4.6
   Compiling lazy_static v1.4.0
   Compiling lock_api v0.3.4
   Compiling net2 v0.2.34
   Compiling iovec v0.1.4
   Compiling signal-hook-registry v1.2.0
   Compiling parking_lot_core v0.7.2
   Compiling parking_lot v0.10.2
   Compiling mio v0.6.22
   Compiling signal-hook v0.1.15
   Compiling crossterm v0.17.3 (/home/omer/rust/crossterm)
error[E0407]: method `execute_winapi` is not a member of trait `Command`
   --> src/terminal.rs:320:5
    |
320 | /     fn execute_winapi(&self) -> Result<()> {
321 | |         sys::set_window_title(self.0)
322 | |     }
    | |_____^ not a member of trait `Command`

error[E0425]: cannot find function `set_window_title` in module `sys`
   --> src/terminal.rs:321:14
    |
321 |         sys::set_window_title(self.0)
    |              ^^^^^^^^^^^^^^^^ not found in `sys`

error: aborting due to 2 previous errors

Some errors have detailed explanations: E0407, E0425.
For more information about an error, try `rustc --explain E0407`.
error: could not compile `crossterm`.

To learn more, run the command again with --verbose.
```

**Comment by osa1** [comment]
Git bisect shows that this is the problematic commit:

```
88add302cd8f006704b712c9f6aa624104635c71 is the first bad commit
commit 88add302cd8f006704b712c9f6aa624104635c71
Author: Matheus Lessa Rodrigues <matheus@fastmail.com>
Date:   Sat May 16 05:41:43 2020 +0000

    Implementing `SetTitle` command (#429)

 src/error.rs                |  1 +
 src/lib.rs                  |  1 +
 src/style/macros.rs         |  2 +-
 src/terminal.rs             | 20 ++++++++++++++++++++
 src/terminal/ansi.rs        |  4 ++++
 src/terminal/sys.rs         |  3 ++-
 src/terminal/sys/windows.rs | 32 ++++++++++++++++++++++++++++++--
 7 files changed, 59 insertions(+), 4 deletions(-)

```

**Comment by osa1** [comment]
It seems like CI is also failing with similar errors.

**Comment by TimonPost** [comment]
Thanks for reporting! That can be correct, this is introduced with this PR #429. Here I said that I would validate the error when releasing the version. I will have a look at it later. You are using master then, right?

**Comment by osa1** [comment]
> So you are using master right?

Yes, though for #431 I had to use an older commit as master doesn't build.

**Comment by TimonPost** [comment]
That should be fine, the changes were mainly in /terminal module.
